### ISSUE TITLE
unable to build using uber toolchain 4.9.3

### ISSUE THREAD

**Issue by shariqislam786** [emceethemouth/kernel_cancro#1]
i am trying to build https://github.com/CM-Cancro/android_kernel_xiaomi_cancro using uber toolchain 4.9.3 on ubuntu 14.04 because it was the same toolchain used for building the kernel used in http://forum.xda-developers.com/xiaomi-mi-3/development/rom-opticancro-t3099530

but i am getting below errors:

net/netfilter/nf_conntrack_core.c: In function 'hash_conntrack_raw':
net/netfilter/nf_conntrack_core.c:73:12: internal compiler error: in get_upper_bound, at graphite-isl-ast-to-gimple.c:529
 static u32 hash_conntrack_raw(const struct nf_conntrack_tuple *tuple, u16 zone)

Can you help?

**Comment by emceethemouth** [comment]
Never had that issue before, I suggest is too double check everything,  I reverted alot of flags since I went back using stock toolchains.

**Comment by Bitti09** [comment]
with stock toolchains : no build problems

**Comment by shariqislam786** [comment]
thanks for help.. i wast trying uber 4.9.3 because it was told that it was used to build in http://forum.xda-developers.com/xiaomi-mi-3/development/rom-opticancro-t3099530 thread
.. i already tried with linaro and getting same error. will give it a try with stock gcc toolchain

**Comment by emceethemouth** [comment]
Stock GCC woludn't have the problem.
